---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  nodes_path: test/integration/nodes

platforms:

- name: ubuntu-16.04
  run_list:
  - "recipe[apt]"

- name: ubuntu-14.04
  run_list:
  - "recipe[apt]"

- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"

- name: debian-7.2.0
  run_list:
  - "recipe[apt]"

- name: centos-7.2
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"

- name: centos-6.8
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"

- name: centos-5.11
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"

- name: fedora-24
  run_list:
  - "recipe[yum]"

- name: fedora-23
  run_list:
  - "recipe[yum]"

- name: fedora-22
  run_list:
  - "recipe[yum]"

- name: fedora-21
  run_list:
  - "recipe[yum]"

# maybe again oneday
 #- name: freebsd-9.2
  #run_list:
  #- "recipe[yum]"

suites:
- name: default
  run_list:
  - "recipe[mongodb]"

- name: default_mongodb_org_repo
  run_list:
  - "recipe[mongodb]"
  attributes:
    mongodb:
      install_method: mongodb-org

- name: replicaset
  run_list:
  - "recipe[mongodb::replicaset]"
  attributes:
    mongodb:
      cluster_name: kitchen
      config:
        replSet: kitchen
  excludes:
    # Upstart is not starting mongodb, status script returns 0 and there are no useful logs. wat?
    - ubuntu-10.04

- name: configserver
  run_list:
  - "recipe[mongodb::configserver]"

- name: mongos
  run_list:
  - "recipe[mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default
      config:
        configdb: my_configserver

- name: mms_monitoring_agent
  run_list:
  - "recipe[mongodb::mms_monitoring_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        monitoring:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart script uses setuid which is not present in this version
    - ubuntu-10.04
    # Upstart is not present
    - debian-7.2.0
    # Package does not create the user
    - centos-5.10

- name: mms_backup_agent
  run_list:
  - "recipe[mongodb::mms_backup_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        backup:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart script uses setuid which is not present in this version
    - ubuntu-10.04
    # Upstart is not present
    - debian-7.2.0
    # Package does not create the user
    - centos-5.10

- name: user_management
  run_list:
  - "recipe[mongodb::default]"
  - "recipe[mongodb::user_management]"
  attributes:
    mongodb:
      install_method: mongodb-org
      # Needed to read the correct config file
      # since mongo 2.6
      default_init_name: mongod
      dbconfig_file: mongodb.conf
      config:
        auth: true
  excludes:
    # Can't connect to mongodb without it running from upstart
    - ubuntu-10.04
