---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
  nodes_path: test/integration/nodes

platforms:
- name: ubuntu-16.04
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: debian-8.5
- name: debian-7.11
- name: centos-7.2
- name: centos-6.8
# wait until DNF provider is working
# - name: fedora-24
# - name: fedora-23
# - name: fedora-22
- name: fedora-21
# maybe again oneday
# - name: freebsd-9.2
#   run_list:
#   - "recipe[yum]"

suites:
- name: default
  run_list:
  - "recipe[mongodb]"

- name: replicaset
  run_list:
  - "recipe[mongodb::replicaset]"
  attributes:
    mongodb:
      cluster_name: kitchen
      config:
        replSet: kitchen

- name: configserver
  run_list:
  - "recipe[mongodb::configserver]"

- name: mongos
  run_list:
  - "recipe[mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default
      config:
        configdb: my_configserver

- name: mms_monitoring_agent
  run_list:
  - "recipe[mongodb::mms_monitoring_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        monitoring:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.11

- name: mms_backup_agent
  run_list:
  - "recipe[mongodb::mms_backup_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        backup:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.11

- name: user_management
  run_list:
  - "recipe[mongodb::default]"
  - "recipe[mongodb::user_management]"
  attributes:
    mongodb:
      install_method: mongodb-org
      # Needed to read the correct config file
      # since mongo 2.6
      default_init_name: mongod
      dbconfig_file: mongodb.conf
      config:
        auth: true
